### PR TITLE
Merging forked repo into original

### PR DESCRIPTION
**Pull request by wyscott123**
Merging our forked repo into your main repo with all the fixes

### CODE REVIEW

**Review by kaneyumin — CHANGES_REQUESTED** [review]
>    myMap.move(myName, new_loc);

this is causing compilation to fail as it is not called correctly.

**Review by kaneyumin — CHANGES_REQUESTED** [review]
>/__w/Team4/Team4/Projects/P2/app/src/main/java/pacman/Ghost.java:48: error: illegal start of expression
> Task :app:compileJava
  public boolean is_pacman_in_range() {
  ^
1 error

It still has compilation errors

**Review by kaneyumin — CHANGES_REQUESTED** [review]
nvm looks good

**Review by kaneyumin — APPROVED** [review]
looks gud

**Comment by wyscott123** [comment]
> nvm looks good

Re-Requested review after fixing our issues, just some stupid bracket stuff

**Pull request merged**
